### ISSUE TITLE
php 5.6.9 Upgrade PCRE errors

### ISSUE THREAD

**Issue by smelchior** [gplessis/dotdeb-php5#85] opened 2015-05-19 10:10 UTC
After upgrading our server to the latest 5.6.9 version we get errors within swiftmailer (same issue as https://github.com/swiftmailer/swiftmailer/issues/259):
preg_match(): Compilation failed: internal error: previously-checked referenced subpattern not found

the swiftmailer ticket suggest that this is somehow a pcre linking issue. 
With php 5.6.8 everything is fine. The changelog for php 5.6.9 mentions a PCRE update, this is probably related?

**Comment by gplessis** [comment] 2015-05-19 12:52
It's probably related.

Dotdeb packages rely on the bundled PCRE library and it looks like its latest update is messing with your code, especially with SwiftMailer's regex. I'm sorry, but I can't change the way PHP is linked to PCRE.

Could you please isolate the faulty code and report it to the SwiftMailer dev team to make it compatible with PCRE 8.37?

**Comment by dmaicher** [comment] 2015-05-19 18:08
Actually the swiftmailer code works just fine using php 5.6.9 in CLI. We only have the issue using it via apache 2 mod php5. So not sure where the issue is exactly? :(

**Comment by liayn** [comment] 2015-05-25 22:06
https://bugs.php.net/bug.php?id=69689

**Comment by gplessis** [comment] 2015-05-28 19:27
Ok. If you need to downgrade, take a look at http://archives.dotdeb.org/

**Comment by d1gi** [comment] 2015-05-30 16:13
gplessis, if I need to downgrade to 5.6.8, what string is needed in /etc/apt/sources.list ?

**Comment by gplessis** [comment] 2015-05-30 16:43
@d1gi : take a look at http://archives.dotdeb.org/, you can get the packages you need and install them manually with `dpkg -i ...`. Unfortunately, it's not a repo.

**Comment by gplessis** [comment] 2015-06-02 19:05
A intermediate release is coming (see 72b99de83c0f6579a33f08d960b1c767dee86f60)

**Comment by gplessis** [comment] 2015-06-03 15:07
Packages of PHP 5.6.9 have been updated a few hours ago. Can you confirm that the problem has been fixed?

**Comment by akrabat** [comment] 2015-06-03 16:14
Doesn't seem fixed here. However, I'm not sure if I have the update?

```
$ php --version
PHP 5.6.9-1~dotdeb+7.2 (cli) (built: Jun  2 2015 19:39:06) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2015, by Zend Technologies

```

but:

```
$ php -i | grep PCR
PCRE (Perl Compatible Regular Expressions) Support => enabled
PCRE Library Version => 8.36 2014-09-26
```

Aren't we suppose to be seeing 8.37?

**Comment by dmaicher** [comment] 2015-06-03 16:40
Unfortunately still the same for me as well :(

**Comment by gplessis** [comment] 2015-06-03 16:46
Yeah, you did update. I'll investigate further to figure out why the PCRE version hasn't been upgraded.

**Comment by d1gi** [comment] 2015-06-04 15:25
no, not fixed.

**Comment by machour** [comment] 2015-06-09 13:02
bug confirmed, still not fixed

**Comment by fgerards** [comment] 2015-06-12 10:13
http://php.net/ChangeLog-5.php#5.6.10 - new versions are out....

**Comment by machour** [comment] 2015-06-12 10:59
It seems that the bug is still present after upgrading to 5.6.10-1~dotdeb+7.1
PCRE Library Version is still set to	8.36 2014-09-26 in phpinfo() ..
am I missing something ?

**Comment by darthmaim** [comment] 2015-06-12 11:00
Confirmed, its still not fixed with `5.6.10-1~dotdeb+7.1`.

**Comment by fgerards** [comment] 2015-06-12 12:09
Well, then you compiled it wrong - the GIT-Source for PHP 5.6.10 is correct in this spot, see: https://github.com/php/php-src/blob/php-5.6.10/ext/pcre/pcrelib/config.h

**Comment by gplessis** [comment] 2015-06-12 14:16
Sorry for this. My source tree is clean (https://github.com/gplessis/dotdeb-php5/blob/master-5.6/wheezy/ext/pcre/pcrelib/config.h). I'll check my CI server.

**Comment by gplessis** [comment] 2015-06-12 23:37
Starting from the sources from www.php.net, I'm still getting a wrong version in  `phpinfo()` :
```
$ tar xf php-5.6.10.tar.xz
$ cd php-5.6.10/
$ grep '^#define VERSION ' ext/pcre/pcrelib/config.h
#define VERSION "8.37"
$ ./configure --disable-all --enable-cli
$ make
$ ./sapi/cli/php -i|grep 'PCRE Library Version'     
PCRE Library Version => 8.36 2014-09-26
```
I tested on several environnements (Dockerized Wheezy, stock Wheezy, OS X). Still the same result.

After some investigation, I found that the "PCRE Library Version" comes from the [`pcre_version()` function from the bundled PCRE library](https://github.com/php/php-src/blob/php-5.6.10/ext/pcre/pcrelib/pcre_version.c#L94) and that the PHP upstream fix is incomplete : `PCRE_MINOR` [has not been changed in pcre.h](https://github.com/php/php-src/blob/php-5.6.10/ext/pcre/pcrelib/pcre.h#L44-L47).

I'll post an update on [bug #69689](https://bugs.php.net/bug.php?id=69689) to make sure that the PCRE update is complete.

**Comment by gplessis** [comment] 2015-06-13 22:57
Guys, I just uploaded new PHP 5.6 packages (versions `5.6.10-1~dotdeb+7.2` and `5.6.10-1~dotdeb+zts+7.2`). Could you please confirm that PCRE 8.37 is displayed? If so, does it fixes your original issue?

**Comment by dmaicher** [comment] 2015-06-13 23:03
Thx for the update. Now the version looks correct:

```
php -v
PHP 5.6.10-1~dotdeb+7.2 (cli) (built: Jun 13 2015 20:08:39) 

php -i | grep PCRE
PCRE Library Version => 8.37 2015-04-28
```

Unfortunately the original problem with the swiftmailer regex using apache2 mod php stays the same :(

**Comment by darthmaim** [comment] 2015-06-13 23:11
Confirming that the version is now reported correctly, but I am still getting the same error.

**Comment by gplessis** [comment] 2015-06-14 18:12
Ok, I suspect PCRE 8.37 - the one bundled with mod_php - to be incompatible with the system PCRE -the one used by Apache. Guys, is this issue happening only with Apache or do you use an alternative SAPI - such as FPM, CGI or FastCGI?

Could you please test the problematic portion of code with another SAPI (CLI, FPM...), see if the issue still happens, and keep me posted? Thanks.

**Comment by akrabat** [comment] 2015-06-14 19:01
Yes. It works with fast-cgi, but not with mod_php.

**Comment by gplessis** [comment] 2015-06-15 05:02
Guys, could you please try one of this new packages, depending on you config :
* libapache2-mod-php5 [amd64](http://ci.dotdeb.org/job/dotdeb-php5/branch/master-5.6%2Fwheezy/lastSuccessfulBuild/artifact/jenkins-dotdeb-php5-master-5.6-wheezy-10/src/libapache2-mod-php5_5.6.10-1%7Edotdeb+7.2_amd64.deb) or [i386](http://ci.dotdeb.org/job/dotdeb-php5/branch/master-5.6%2Fwheezy/lastSuccessfulBuild/artifact/jenkins-dotdeb-php5-master-5.6-wheezy-10/src/libapache2-mod-php5_5.6.10-1%7Edotdeb+7.2_i386.deb)
* libapache2-mod-php5filter [amd64](http://ci.dotdeb.org/job/dotdeb-php5/branch/master-5.6%2Fwheezy/lastSuccessfulBuild/artifact/jenkins-dotdeb-php5-master-5.6-wheezy-10/src/libapache2-mod-php5filter_5.6.10-1%7Edotdeb+7.2_amd64.deb) or [i386](http://ci.dotdeb.org/job/dotdeb-php5/branch/master-5.6%2Fwheezy/lastSuccessfulBuild/artifact/jenkins-dotdeb-php5-master-5.6-wheezy-10/src/libapache2-mod-php5filter_5.6.10-1%7Edotdeb+7.2_i386.deb)

The change is that Apache modules are now built against the system PCRE. It should avoid conflict with the one included in Apache - it's now basically the same. No change for the other SAPIs (details [here](https://github.com/gplessis/dotdeb-php5/commit/fe6756dae96833e158b919a82b8bf7b8b053afb0)).

Please keep me posted.

**Comment by akrabat** [comment] 2015-06-15 05:49
@gplessis The new amd64 deb works for me. Thanks.

**Comment by xkobal** [comment] 2015-06-15 06:19
It's fixed for libapache2-mod-php5 amd64
Thanks

**Comment by xkobal** [comment] 2015-06-15 06:25
I have tested on Debian 7 and it's the same for me with : 
libapache2-mod-php5                5.6.10-1~dotdeb+7.2           amd64

**Comment by gplessis** [comment] 2015-06-15 06:32
@xkobal : "the same for me" << do you me that it is working now or not?

If it's still not working, could you please :
* publish a `phpinfo()`
* post here the problematic code
* publish a page with the above code showing the exact error

Thanks

**Comment by xkobal** [comment] 2015-06-15 06:36
Does not work (sorry for my previous message).

The code which does not work is the Swiftmailer regex, here is the error: 
Jun 15 08:24:08 jfg-stage-internal-1 apache2: PHP Fatal error:  Uncaught exception 'Swift_RfcComplianceException' with message 'Address in mailbox given [developers@jfg-networks.net] does not comply with RFC 2822, 3.6.2.' in /home/web/OverblogUser-654/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php:348#012Stack trace:#012#0 /home/web/OverblogUser-654/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php(263): Swift_Mime_Headers_MailboxHeader->_assertValidAddress('developers@jfg-...')#012#1 /home/web/OverblogUser-654/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php(106): Swift_Mime_Headers_MailboxHeader->normalizeMailboxes(Array)#012#2 /home/web/OverblogUser-654/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php(63): Swift_Mime_Headers_MailboxHeader->setNameAddresses(Array)#012#3 /home/web/OverblogUser-654/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleMimeEntity.php(602): Swift_Mime_Headers_MailboxHeader->setFieldBodyModel(Array)#012#4 /home/web/OverblogUser-65 in /home/web/OverblogUser-654/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php on line 348

I can't provide phpinfo, because I rollback my servers, but here is the list of installed packages:

**Comment by gplessis** [comment] 2015-06-15 06:40
@xkobal : you're using PHP 5.5, that hasn't been fixed yet. I'll published 5.5.26 soon.

**Comment by gplessis** [comment] 2015-06-15 06:41
@akrabat thanks for your feedback.

**Comment by xkobal** [comment] 2015-06-15 06:41
No sorry, that was my rollback server dpkg, I use 5.6.10-1~dotdeb+7.2

**Comment by gplessis** [comment] 2015-06-15 06:46
@xkobal did you use the one from my above comment, install it with `dpkg -i` and restart your Apache server completely? Please give it one more try, see if the issue is fixed or not and please give me the value of "Build Date" shown at the beginning of your Apache's `phpinfo()`, before downgrading.

Thanks.

**Comment by xkobal** [comment] 2015-06-15 06:52
OK, works for me ;-) I thought that the libapache2-mod-php5 was published.

**Comment by gplessis** [comment] 2015-06-15 06:55
@xkobal no, I wanted to make sure that the issue was fixed before releasing new packages.

A fixed PHP 5.6 is currently building. PHP 5.5 and 5.4 should follow.

**Comment by mybigman** [comment] 2015-06-15 07:23
@gplessis thanks...

Ive been pulling my hair out all day... glad your working on the 5.5 version.

**Comment by koceg** [comment] 2015-06-15 10:42
[Latest build](http://ci.dotdeb.org/job/dotdeb-php5/branch/master-5.6%2Fwheezy/lastSuccessfulBuild/artifact/jenkins-dotdeb-php5-master-5.6-wheezy-11/src/libapache2-mod-php5_5.6.10-1~dotdeb+7.3_amd64.deb) worked for me, thanks.

**Comment by gplessis** [comment] 2015-06-15 17:16
`5.6.10-1~dotdeb+7.3` and `5.6.10-1~dotdeb+zts+7.3`have been published.

**Closed by gplessis** 2015-06-15 17:16 UTC

**Comment by darthmaim** [comment] 2015-06-15 19:14
Works great, thanks for that! :+1:

**Comment by dmaicher** [comment] 2015-06-15 19:47
Also fixed here. Thx! :)

**Comment by akrabat** [comment] 2015-06-15 20:04
Fixed here too. Thank you @gplessis.

**Comment by MichaelUbuntu** [comment] 2015-06-16 14:34
on php 5.5 exist exakt the same error !

php -v
PHP 5.5.25-1~dotdeb+7.1 (cli) (built: May 15 2015 16:39:22)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2015, by Zend Technologies
    with Xdebug v2.3.2, Copyright (c) 2002-2015, by Derick Rethans

php -i | grep PCRE
PCRE (Perl Compatible Regular Expressions) Support => enabled
PCRE Library Version => 8.36 2014-09-26

**Comment by machour** [comment] 2015-06-16 14:39
@MichaelUbuntu built: *May 15* 2015 16:39:22
You should probably apt-get update. If the date doesn't change, it means that PHP 5.5 packages are not ready yet and that you should probably reopen this as a reminder for @gplessis ;)

**Comment by MichaelUbuntu** [comment] 2015-06-16 14:49
yes i have already done the following:
apt-get update && apt-get upgrade

but nothing changed in php 5.5

**Comment by gplessis** [comment] 2015-06-16 15:13
fixed PHP 5.5 and PHP 5.4 packages will be published today. Thanks for your patience.

**Comment by MaZderMind** [comment] 2015-06-17 07:58
just a nuisance:

apcu does not load on cli anymore, becuause of undefined symbol: pcre_exec:
````
php -m
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php5/20121212/apcu.so' - /usr/lib/php5/20121212/apcu.so: undefined symbol: pcre_exec in Unknown on line 0
````

But as apcu does nothing useful on cli anyway, it's easy to disable it:
````
php5dismod -s cli apcu
````

Works in Apache nicely, though.

**Comment by gplessis** [comment] 2015-06-17 14:11
@MaZderMind ok, switch to #81 for this issue

**Comment by MichaelUbuntu** [comment] 2015-06-17 18:14
thanks problem is solved

**Comment by gplessis** [comment] 2015-06-18 22:55
FYI, I had to use the system PCRE for all the SAPIs to avoid conflicts with PECL extensions. Don't bother  if you see PCRE reported as "8.30 2012-02-04" on PHP 5.5. I'll propagate the changes on all PHP versions soon.
